# Visit epicmc.us/account to claim an access_token. You can't query any EPICMC API without one.
---
access_token: '32 character access_token goes here'

#Use ยง and a number for color. Ex: ยง1EPICMC will show a blue text saying EPICMC
ServerName: ยง2EPICMC
